### ISSUE TITLE
doing builds directly on the host is an antipattern

### ISSUE THREAD

**Issue by cgwalters** [johnbieren/atomic_testing#1]
I am trying to push for this to be considered an anti-pattern:

```
  - name: Install required packages on atomic host
    shell: "rpm-ostree install {{ item }}"
    with_items:
      - libseccomp-devel
      - gcc
```

Basically instead, provision a container with the host's `/` bind mounted as `/host` or whatever, like we encourage with the tools container.  See this for example:
https://github.com/projectatomic/bubblewrap/blob/master/.redhat-ci.yml
which just calls:
https://github.com/projectatomic/bubblewrap/blob/master/ci/redhat-ci.sh

This is also something I push for with [Atomic Workstation](https://lists.fedoraproject.org/archives/list/desktop@lists.fedoraproject.org/thread/JDBGLC2MCXWPHAPULN6PKUKFRE2SS7GT/).  Atomic Workstation doesn't have gcc installed by default (unlike Fedora Workstation), and on it I do all my development inside "pet" containers.
